- name: Create lab environment
  hosts: localhost
  connection: local
  tasks:
  - name: Generate SSH keys
    openssh_keypair:
      path: ~/.ssh/lab_rsa
  - name: Terraform apply
    terraform:
      lock: no
      force_init: true
      project_path: './'
      state: present
  - name: Configure local alias
    blockinfile:
      path: ~/.bashrc
      state: present
      block: |
        alias bastion='ssh -i ~/.ssh/lab_rsa azureadmin@`terraform output bastion_ip`'
  - name: Terraform refresh
    shell: terraform refresh ; . ~/.bashrc
  - name: Set bastion env variable
    shell: echo { \"rg\":\"`terraform output rg`\" } > rg.json
  - name: Include vars of stuff.yaml into the 'stuff' variable
    include_vars:
      file: rg.json
      name: stuff
  - name: Configure dynamic inventory file
    blockinfile:
      path: ./myazure_rm.yml
      state: present
      block: |
        include_vm_resource_groups:
        - {{ stuff["rg"] }}
  - name: Refresh inventory to ensure new instances exist in inventory
    meta: refresh_inventory

- name: Zypper update
  hosts: all
  remote_user: azureadmin
  become: yes
  tasks:
  - name: Zypper update
    command: sudo zypper ref

- name: Push SSH key to bastion
  hosts: tag_group_bastion
  remote_user: azureadmin
  become: yes
  tasks:
  - name: Push SSH azureadmin private key
    copy:
      src: ~/.ssh/lab_rsa
      dest: /home/azureadmin/.ssh/id_rsa
      mode: '0600'
      owner: azureadmin
      group: users
  - name: Configure etc hosts
    blockinfile:
      path: /etc/hosts
      state: present
      block: |
        # Cluster nodes
        10.0.0.6 node0
        10.0.0.7 node1

- name: Push SSH config
  hosts: all
  remote_user: azureadmin
  tasks:
  - name: Push SSH config to all VMs
    copy:
      src: ssh.config/ssh.config
      dest: /home/azureadmin/.ssh/config
      owner: azureadmin
      group: users

- name: Push root SSH keys to nodes
  hosts: tag_group_node0 tag_group_node1
  remote_user: azureadmin
  become: yes
  tasks:
  - name: Create /root/.ssh directory
    file:
      path: /root/.ssh/
      state: directory
      mode: '0700'
  - name: Copy root private key
    copy:
      src: ~/.ssh/lab_rsa
      dest: /root/.ssh/id_rsa
      owner: root
      group: root
      mode: '0600'
  - name: Copy root public key to authorized keys
    copy:
      src: ~/.ssh/lab_rsa.pub
      dest: /root/.ssh/authorized_keys
      owner: root
      group: root
      mode: '0644'
  - name: Copy root public key to .ssh
    copy:
      src: ~/.ssh/lab_rsa.pub
      dest: /root/.ssh/id_rsa.pub
      owner: root
      group: root
      mode: '0644'

- name: Set initiator name node0
  hosts: tag_group_node0
  remote_user: azureadmin
  become: yes
  tasks:
  - name: Change initiator name
    copy:
      src: node.config/node0.initiator.config
      dest: /etc/iscsi/initiatorname.iscsi
      owner: root
      group: root

- name: Set initiator name node1
  hosts: tag_group_node1
  remote_user: azureadmin
  become: yes
  tasks:
  - name: Change initiator name
    copy:
      src: node.config/node1.initiator.config
      dest: /etc/iscsi/initiatorname.iscsi
      owner: root
      group: root

- name: Configure nodes
  hosts: tag_group_node0 tag_group_node1
  remote_user: azureadmin
  become: yes
  tasks:
  - name: Enable iscsid
    service:
      name: iscsid
      enabled: yes
  - name: Enable iscsi
    service:
      name: iscsi
      enabled: yes
  - name: Enable sbd
    command: sudo systemctl enable sbd
  - name: Start iscsid
    service:
      name: iscsid
      state: restarted
  - name: Start iscsi
    service:
      name: iscsi
      state: restarted
  - name: Retrieve IDs of iSCSI devices, Create the SBD devices, Adapt the SBD config
    script: node.config/node.sbd.config.py
    args:
      executable: python
      creates: /etc/delete.to.retry.node.sbd.config.py
  - name: Create the softdog configuration file
    copy:
      src: node.config/node.softdog.config
      dest: /etc/modules-load.d/softdog.conf   
  - name: Load softdog module
    command: sudo modprobe -v softdog
  - name: Install socat
    zypper:
      name: socat
      state: present
  - name: Install resource-agents
    zypper:
      name: resource-agents
      state: present
  - name: Configure systemd
    copy:
      src: node.config/node.systemd.config
      dest: /etc/systemd/system.conf
      owner: root
      group: root  
      mode: '0644'
  - name: Reload daemon-reload
    command: sudo systemctl daemon-reload 
  - name: Configure systemd
    copy:
      src: node.config/node.sysctl.config
      dest: /etc/sysctl.conf
      owner: root
      group: root  
      mode: '0644'
  - name: Configure interface
    run_once: true
    copy:
      src: node.config/node.interface.config
      dest: /etc/sysconfig/network/ifcfg-eth0
      owner: root
      group: root  
      mode: '0644'
  - name: Install fence-agents
    zypper:
      name: fence-agents
      state: present

- name: Configure node node0
  hosts: tag_group_node0
  remote_user: azureadmin
  become: yes
  tasks:
  - name: Stop corosync
    command: sudo service corosync stop
    args:
      creates: /etc/corosync/corosync.conf
  - name: Stop pacemaker
    command: sudo service pacemaker stop
    args:
      creates: /etc/corosync/corosync.conf
  - name: Configure ha-cluster-init
    expect:
      command: sudo ha-cluster-init -u
      echo: yes
      creates: /etc/corosync/corosync.conf
      responses:
        "Do you want to continue anyway (y/n)?": "y"
        "/root/.ssh/id_rsa already exists - overwrite (y/n)?": "n"
        '  Address for ring0': ""
        "  Port for ring0": ""
        "Do you wish to use SBD (y/n)?": "y"
        "Do you wish to configure a virtual IP address (y/n)?": "n"
        'csync2 is already configured - overwrite (y/n)?': 'y'
        '/etc/corosync/authkey already exists - overwrite (y/n)?': 'y'        
        '/etc/pacemaker/authkey already exists - overwrite (y/n)?': 'y'
        'SBD is already configured to use': 'n'
  - name: Update corosync config
    copy:
      src: node.config/node.corosync.config
      dest: /etc/corosync/corosync.conf
  - name: Restart corosync
    command: sudo service corosync restart

- name: Configure node1
  hosts: tag_group_node1
  remote_user: azureadmin
  become: yes
  tasks:
  - name: Stop corosync
    command: sudo service corosync stop
    args:
      creates: /etc/corosync/corosync.conf
  - name: Stop pacemaker
    command: sudo service pacemaker stop
    args:
      creates: /etc/corosync/corosync.conf
  - name: Join node to cluster
    expect:
      command: sudo ha-cluster-join
      echo: yes
      creates: /etc/corosync/corosync.conf
      responses:
        'Do you want to continue anyway (y/n)?': 'y'
        '  IP address or hostname of existing node': '10.0.0.6'
        '/root/.ssh/id_rsa already exists - overwrite (y/n)?': 'n'
        '  Address for ring0': ''
  - name: Update corosync config
    copy:
      src: node.config/node.corosync.config
      dest: /etc/corosync/corosync.conf
  - name: Restart corosync
    command: sudo service corosync restart

- name: Configure node0
  hosts: tag_group_node0
  remote_user: azureadmin
  become: yes
  tasks:
  - name: Configure stonith device
    script: node.config/node.stonith.config.sh
    args:
      creates: /etc/delete.to.retry.node.stonith.config.sh