- name: Create lab environment
  hosts: localhost
  connection: local
  tasks:
  - name: Generate SSH keys
    openssh_keypair:
      path: ~/.ssh/lab_rsa
  - name: Terraform apply
    terraform:
      lock: no
      force_init: true
      project_path: './'
      state: present
  - name: Configure local alias
    blockinfile:
      path: ~/.bashrc
      state: present
      block: |
        alias bastion-uswest2='ssh -i ~/.ssh/lab_rsa azureadmin@`terraform output bastion_ip_westus2`'
  - name: Set bastion env variable
    shell: echo rg:`terraform output rg` > rg.yaml 
  - name: Include vars of stuff.yaml into the 'stuff' variable (2.2).
    include_vars:
      file: rg.yaml
      name: rg
  - name: Configure dynamic inventory file
    blockinfile:
      path: ./myazure_rm.yml
      state: present
      block: |
        include_vm_resource_groups:
        - {{ rg }}
  - name: Refresh inventory to ensure new instances exist in inventory
    meta: refresh_inventory

- name: Zypper update
  hosts: all
  remote_user: azureadmin
  become: yes
  tasks:
  - name: Zypper update
    command: sudo zypper ref